# Control Structure and Functions

- Control Structures
    - A
        - Execute certain commands only when certain condition(s) is (are) satisfied(if-then-else)
        - Execute certain commands repeatedly and use a certian logic to stop the iteration(for, while, loops)
    - If elif family  : -
        - if, if else and if-elif-else are a family of constructs where :
            - A condition is first checked, if it is satisfied then operations are performed
            - if Condition is not satisfied, code exist construct or moves on to other options
    - for : - 
        - Execute certain commands repeatedly and use a certain logic to stop the iteration(for  loops)
    - while :- 
        - A while loop is used when a set of commands are to be executed depending on a specific condition  (while (condition is satisfied):
                                        statements)
-  Functions :- 
    - A functions accepts input arguments and produces an output by executing valid commands present in the function
    - Function name and file names need not be the same
    - A file can have one or more function definitions
    - Functions are created using the command def and a colon with the statementto be executed indented as a block
        - def function_name(parameters):
            - statements
        - Converting the Age variable from months to years by defining a function
        - The converted values will be stored in a new column, 'Age_Converted'
        - Hence, inderting a new column
            - cars_data1.insert(11,"Age_Converted",0)

- Example : if else and for loops    
    - we will create 3 bins from the 'Price' variable using if else and for loops
    - The binned values will be stored as classes in a new column, 'price class'

In [11]:
import pandas as pd
cars_data = pd.read_csv('Toyota.csv')
# cars_data = pd.read_csv('Toyota.csv', index_col=0)
cars_data1=pd.read_table('Toyota.csv',delimiter=" ",index_col=(0))

In [12]:
cars_data1.insert(10,"Price_Class", "")

In [ ]:
for i in range(0,len(cars_data1['Price']),1):
    if(cars_data1['Price'][i]<=8450):
        cars_data1['Price_Class'][i]="Low"
    elif ((cars_data1['Price'][i]>11950)):
        cars_data1['Price_Class'][i]="High"
    else: cars_data1['Price_Class'][i]="Medium"

- A for loop is implemented and the observations are separated into three categories: 
    - Price 
        - upto 8450
        - between 8450 & 11950
        - greater than 11950
- The classes have been stored in a new column 'Price_Class'

In [14]:
i = 0
while i<len(cars_data1['Price']):
    if(cars_data1['Price'][i]<=8450):
        cars_data1['Price_Class'][i]="Low"
    elif ((cars_data1['Price'][i]>11950)):
        cars_data1['Price_Class'][i]="High"
    else: cars_data1['Price_Class'][i]="Medium"
    i=i+1

C:\Users\user\AppData\Local\Temp\ipykernel_8148\602737658.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cars_data1['Price_Class'][i]="High"
C:\Users\user\AppData\Local\Temp\ipykernel_8148\602737658.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cars_data1['Price_Class'][i]="Low"
C:\Users\user\AppData\Local\Temp\ipykernel_8148\602737658.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  else: cars_data1['Price_Class'][i]="Medium"

- Example : while loop
    - A while loop is used whenever you want to execute statement until a specific condition is violated
    - Here a while loop is used over the length of the column 'Price_Class' and an if else loop is used to bin the values and stored it as classes

- Series.value_counts()     returns series containing count of unique values

In [15]:
cars_data1['Price_Class'].value_counts() 
#  numerical to categorical

High      3
Low       1
Medium    1
Name: Price_Class, dtype: int64

- Example A: 
    - Functions: 
        - Here, a function c_convert has been defined 
        - The function takes agruments and returns one value

- Functoin with multiple inputs and outputs Example B: 
    - Functions in python takes multiple input objects but return only one object as output
    - However lists, tuples or dictionaries can be used to return multiple outputs as required

In [16]:
# A: 
def c_convert(val):
    val_converted = val/12
    return val_converted

cars_data1["Age_Converted"]=c_convert(cars_data1['Age'])
cars_data1["Age_Converted"]=round(cars_data1["Age_Converted"],1)

# B : 
- Example : 
    - Converting the Age variable from months to years and getting kilometers (KM) run per month
    - The converted values fo kilometer will be will be stored in a new column, 'km_per_month'
    - Hence, inserting a new column 
        - cars_data1.insert(12,"Km_per_month",0)
- A multiple input multiple output function c_convert has been defined
    - the function takes in two inputs
    - The output is returned in the form of a list

- Here, Age and KM column of the dataset are input to the function
- The outputs are assigned to 'Age_Converted' and 'km_per_month'

In [17]:
def c_convert(val1,val2):
    val_converted = val1/12
    ratio         = val2/val1
    return [val_converted, ratio]

cars_data1["Age_Converted"],cars_data1["Km_per_month"] = \
    c_convert(cars_data1['Age'],cars_data1['KM'])

In [18]:
cars_data1.head()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Price_Class,Weight,Age_Converted,Km_per_month
0,1,13500,23,46986,Diesel,90,1.0,0,2000,three,High,1167,1.916667,2042.869565
1,2,7900,34,74344,Petrol,90,1.0,0,2000,2,Low,1145,2.833333,2186.588235
2,3,11189,29,61090,CNG,90,NaN,0,2000,3,Medium,1189,2.416667,2106.551724
3,4,13500,23,46986,Diesel,90,1.0,0,2000,3,High,1165,1.916667,2042.869565
4,5,13750,23,72937,Diesel,90,1.0,0,2000,3,High,1165,1.916667,3171.173913

# Exploratory data analysis

- 1. Frequency tables
- 2. Two - way tables
- 3. Two - way table - joint probability
- 4. Two - way table - Marginal probability 
- 5. Two - way table - Conditional probability
- 6. Correlation 
    - 09-05-22

In [19]:
# import pandas as pd
# cars_data=pd.read_csv('Toyota.csv',index_col=0,na_values=["??","????"])
# cars_data2 = cars_data.copy()
import pandas as pd
cars_data = pd.read_csv('Toyota.csv')
cars_data = pd.read_csv('Toyota.csv', index_col=0)
cars_data2=pd.read_table('Toyota.csv',delimiter=" ",index_col=(0))

- frequency tables
    - pandas.crosstab()
        - To compute a simple cross-tabulation of one, two(or more) factors
        - By default computes a frequency table of the factors
            - pd.crosstab(index=cars_data1['FuelType'],columns='count',dropna=True)
- Two-wway tables
    - To look at the frequency distribution of gearbox types with respect to different fuel types of the cars
        - pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], dropna=True)
- Two-way table 
    - joint Probability is the likelihood of two independent events happening at the same time.
        - pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize=True, dropna=True)
- Two-way table 
    - marginal probability
        - Marginal probability is the probability of the occurrence of the single event 
            - pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], margins=True, normalize=True, dropna=True)
- Two-way table 
    - Conditional probability
        - Conditonal probability is the probability of an event (A), given that another event (B) has already occurred
        - Given the type of gear box, probability of different fuel type 
            - pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize='index', dropna=True)
            - pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize='columns', margins=True, dropna=True)
- Correlation 
    - : The strength of association between two variables 
    - Visual representation of correlation : Scatter plots
        - Positive trend
        - Negative trend
        - Little or no correlation
    - To compute pairwise correlation of columns excluding NA/null values
    - Excluding the categorical variables to find the Pearson's correlation
        - DataFrame.corr(self, method='Pearson')
            - numerical_data = cars_data2.select_dtypes(exclude=[object])
            - print(numerical_data.shape)

In [20]:
pd.crosstab(index=cars_data2['FuelType'],columns='count',dropna=True)

col_0     count
FuelType
CNG           1
Diesel        3
Petrol        1

In [21]:
pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0            1       3       1

In [23]:
pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize=True, dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0          0.2     0.6     0.2

In [22]:
pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], margins=True, normalize=True, dropna=True)

FuelType   CNG  Diesel  Petrol  All
Automatic
0          0.2     0.6     0.2  1.0
All        0.2     0.6     0.2  1.0

In [24]:
pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize='index', dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0          0.2     0.6     0.2

In [25]:
pd.crosstab(index   = cars_data2['Automatic'], columns=cars_data2['FuelType'], normalize='columns', margins=True, dropna=True)

FuelType   CNG  Diesel  Petrol  All
Automatic
0          1.0     1.0     1.0  1.0

In [26]:
numerical_data = cars_data2.select_dtypes(exclude=[object])
print(numerical_data.shape)

(5, 9)

In [27]:
corr_matrix = numerical_data.corr() # correlation between numerical variables 
print(corr_matrix)

            Unnamed: 0     Price       Age        KM  HP  MetColor  Automatic  \
Unnamed: 0    1.000000  0.385605 -0.349250  0.290888 NaN       NaN        NaN
Price         0.385605  1.000000 -0.991853 -0.569544 NaN       NaN        NaN
Age          -0.349250 -0.991853  1.000000  0.588361 NaN       NaN        NaN
KM            0.290888 -0.569544  0.588361  1.000000 NaN       NaN        NaN
HP                 NaN       NaN       NaN       NaN NaN       NaN        NaN
MetColor           NaN       NaN       NaN       NaN NaN       NaN        NaN
Automatic          NaN       NaN       NaN       NaN NaN       NaN        NaN
CC                 NaN       NaN       NaN       NaN NaN       NaN        NaN
Weight        0.162221  0.421269 -0.310320 -0.347941 NaN       NaN        NaN

            CC    Weight
Unnamed: 0 NaN  0.162221
Price      NaN  0.421269
Age        NaN -0.310320
KM         NaN -0.347941
HP         NaN       NaN
MetColor   NaN       NaN
Automatic  NaN       NaN
CC         NaN       NaN
Weight     NaN  1.000000